# Generated by Django 4.2.1 on 2023-06-08 16:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Имя')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, upload_to='artists_pics', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.artist')),
            ],
        ),
        migrations.CreateModel(
            name='RoleType',
            fields=[
                ('title', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='Роль')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='Тег')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название')),
                ('cover', models.ImageField(blank=True, upload_to='song_covers', verbose_name='Обложка')),
                ('audio', models.FileField(upload_to='audio', verbose_name='Аудиофайл')),
                ('release_date', models.DateField(blank=True, verbose_name='Дата выпуска')),
                ('upload_date', models.DateField(default=datetime.datetime.now, verbose_name='Дата загрузки')),
                ('role', models.ManyToManyField(blank=True, to='main.role')),
                ('tags', models.ManyToManyField(blank=True, default=None, to='main.tag')),
            ],
        ),
        migrations.AddField(
            model_name='role',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.roletype'),
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название')),
                ('create_date', models.DateField(default=datetime.datetime.now, verbose_name='Дата создания')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('songs', models.ManyToManyField(blank=True, to='main.song')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название')),
                ('release_date', models.DateField(verbose_name='Дата выпуска')),
                ('cover', models.ImageField(blank=True, upload_to='albums_covers', verbose_name='Обложка')),
                ('songs', models.ManyToManyField(blank=True, to='main.song')),
            ],
        ),
    ]
