# Generated by Django 4.2.1 on 2023-06-15 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_artist_photo_alter_song_role_view_userinfo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='authors',
            field=models.ManyToManyField(blank=True, default=None, to='main.artist'),
        ),
        migrations.AlterField(
            model_name='roletype',
            name='title',
            field=models.CharField(default='Автор', max_length=64, primary_key=True, serialize=False, verbose_name='Роль'),
        ),
    ]
