# Generated by Django 4.2.1 on 2023-06-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_like_song_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, to='main.like'),
        ),
        migrations.AddField(
            model_name='album',
            name='tags',
            field=models.ManyToManyField(blank=True, default=None, to='main.tag'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, to='main.like'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='tags',
            field=models.ManyToManyField(blank=True, default=None, to='main.tag'),
        ),
    ]
